- hosts: workstation
  sudo: false

  tasks:
    - name: Install dependencies
      homebrew:
        name: icu4c
        state: present

    - name: Install nokogiri dependency
      shell: sudo gem install nokogiri -- --use-system-libraries --with-xml2-include=/usr/include/libxml2 --with-xml2-lib=/usr/lib

    - name: Install charlock_holmes dependency
      shell: sudo gem install charlock_holmes -- --with-icu-lib=/usr/local/opt/icu4c/lib --with-icu-include=/usr/local/opt/icu4c/include

    - name: Install redcloth dependency for rendering textile pages
      sudo: true
      gem:
        name: RedCloth
        state: present

    - name: Install gollum
      sudo: true
      gem:
        name: gollum
        state: present
